steps:
  # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/awang265/wangle-cloud-platform-backend.git', 'source'] 

  # Step 2: Install dependencies and run tests
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd source/functions
        pip install -r requirements.txt
        python -m unittest tests.py

  # Step 3: Deploy Cloud Function if tests pass
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    dir: 'source/functions'
    args:
      - '-c'
      - |
        if [ $? -eq 0 ]; then
          gcloud functions deploy wcp-function --runtime=python312 --trigger-http --project=glassy-ion-406900 --region=us-central1
        else
          echo "Tests failed. Deployment skipped."
        fi